### ISSUE TITLE
Error when running on non-IU clusters

### ISSUE THREAD

**Issue by bacaron** [faskowit/app-multiAtlasTT#11]
Hello,

This is a fantastic app and would be great to have on other non-IU cluster resources. However, there's a check and call to load a module in the main script that doesn't identify well if the job is being launched on IU cluster or not. This causes the app to fail if the cluster used is nonIU.

I believe the current check looks for the $FREESURFER_HOME file and runs 'module load freesurfer' if not present. Is there potentially a better check to use?

Thank you,
Brad

**Comment by faskowit** [comment]
alrighty-- I think the quick change on the module load line should prevent it from erring if run on a different cluster. check it out!

**Comment by faskowit** [comment]
(on main branch)

**Comment by bacaron** [comment]
Thanks @faskowit! Looks like that worked!
