### ISSUE TITLE
App is failing with "module: command not found"

### ISSUE THREAD

**Issue by soichih** [faskowit/app-multiAtlasTT#14]
Our users are reporting the following error message.

```
+ module load freesurfer
./main: line 36: module: command not found
```

We should not use `module load freesurfer` as it doesn't work on most of our resources, and even if it does, we don't know which version of freesurfer it's pulling (and may change in the future). 

I recommend dropping this, and instead always use the freesurfer that comes with a container that you specify.

**Comment by mohammadhadiarabi** [comment]
Also, I see this error:
Error: (SSH) Channel open failure: open failed

**Comment by faskowit** [comment]
I thought I fixed this problem with the following line: https://github.com/faskowit/app-multiAtlasTT/blob/master/main#L36

The '||' makes it so the error is caught.

**Comment by faskowit** [comment]
looks like brainlfie app was pulling from 0.0.6.... I change to 0.0.7.  This should fix the issue.  Let me know.

**Comment by faskowit** [comment]
Also, @mohammadhadiarabi I don't really understand that error message without more context. I am not sure how it would relate to the modules command.  Hopefully, it goes away in 0.0.7!

**Comment by soichih** [comment]
Thanks @faskowit 0.0.7 worked. 

By the way, it looks like the master branch is more similar to 0.0.6 than 0.0.7. Maybe you should merge the changes you made on 0.0.7 to master?
