### ISSUE TITLE
out of memory on lonestar5

### ISSUE THREAD

**Issue by soichih** [faskowit/app-multiAtlasTT#15]
Is it possible to increase the vmem requirement for this App? When this app runs on a resource for the first time, it often dies with out-of-memory while creating a SIF image.

```
slurmstepd: error: Detected 1 oom-kill event(s) in step 3251101.batch cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
slurmstepd: error: get_exit_code task 0 died by signal
```

```
INFO:    Creating SIF file...
FATAL:   Unable to handle docker://faskowit/app-multiatlastt:0.0.5 uri: unable to build: while creating squashfs: create command failed: exit status 1: 
FATAL ERROR: Out of memory (cache_alloc)
```

I think vmem=16GB should get passed this step.. but I am not sure.

**Comment by faskowit** [comment]
sure sure, should I cut a new release with more vmem???  Also, on my newer branched 0.0.6 and 0.0.7... the docker builds are failing... hmmm....
