### ISSUE TITLE
module: command not found

### ISSUE THREAD

**Issue by soichih** [faskowit/app-multiAtlasTT#16]
This is for the old version (Multi-Atlas Transfer Tool - old) but I've seen users running into this error message

```
+ module load freesurfer
./main: line 36: module: command not found
```

Not all resources have module command, and we also don't know which version of freesurfer gets loaded, so maybe we should not rely on module?

**Comment by faskowit** [comment]
I thought I was able to catch the error with the || on this line: https://github.com/faskowit/app-multiAtlasTT/blob/master/main#L36

**Comment by soichih** [comment]
That is true.. I must have picked the wrong error message when I was looking.. I will reopen this when I find the failing job again.

**Comment by faskowit** [comment]
But there is another good point here... for future work, it probably won't be ideal to support two versions of the maTT app.  After I finish my dissertation writing... I should revisit making the surfaces work with the new freesurfer-mini container...

Maybe the answer could be... run reprozip on it one time with the full FreeSurfer docker... make a docker out of that reprozip'ed container... then make a new dockerfile that imports all the atlas data (therefore "adding that data back in").

**Comment by soichih** [comment]
That sounds good @faskowit 

About reprozip.. @bacaron and I were discussing a need to create a container that has fsl/ants/mcr all together. The size of the container will be extreme, and I was wondering if we could reprozip. If you try reprozip, I'd like to learn from you how we can use it to reduce the container size.
